### ISSUE TITLE
absent required param gitdir of isomorphic-git:pull

### ISSUE THREAD

**Issue by DK-2013** [Hexlet/cli#7]
https://github.com/Hexlet/cli/blob/7f7e6bee55635ac6e86a1215aa9ea4ca755c3beb/src/commands/program/submit.js#L34
https://isomorphic-git.org/docs/en/pull

`hexlet program submit devops-for-programmers vagrant`

rise error:

```
TypeError: Cannot read property 'split' of null
    at new GitConfig (/home/dietmar/.nvm/versions/node/v14.16.0/lib/node_modules/@hexlet/cli/node_modules/isomorphic-git/index.cjs:1464:30)
    at Function.from (/home/dietmar/.nvm/versions/node/v14.16.0/lib/node_modules/@hexlet/cli/node_modules/isomorphic-git/index.cjs:1487:12)
    at Function.get (/home/dietmar/.nvm/versions/node/v14.16.0/lib/node_modules/@hexlet/cli/node_modules/isomorphic-git/index.cjs:1603:22)
    at async _fetch (/home/dietmar/.nvm/versions/node/v14.16.0/lib/node_modules/@hexlet/cli/node_modules/isomorphic-git/index.cjs:7153:18)
    at async _pull (/home/dietmar/.nvm/versions/node/v14.16.0/lib/node_modules/@hexlet/cli/node_modules/isomorphic-git/index.cjs:8732:49)
    at async Object.pull (/home/dietmar/.nvm/versions/node/v14.16.0/lib/node_modules/@hexlet/cli/node_modules/isomorphic-git/index.cjs:10856:12)
    at async Object.handler (/home/dietmar/.nvm/versions/node/v14.16.0/lib/node_modules/@hexlet/cli/src/commands/program/submit.js:31:3) {
  caller: 'git.pull'
} 
```
https://github.com/isomorphic-git/isomorphic-git/blob/89c0da78d5ebf3c9f2754b3c8d557155dd70c8d7/src/managers/GitConfigManager.js#L8

**Comment by DK-2013** [comment]
https://isomorphic-git.org/docs/en/dir-vs-gitdir
))
